### ISSUE TITLE
Aggiungere disclaimer conversione al README

### ISSUE THREAD

**Issue by Fupete** [italia/design-ui-kit-template#1]
### Esiste già una discussione sul tema che ti interessa, o su un tema simile?

- [X] Ho verificato e non esiste

### Cosa

@astagi seppure dai nostri test appare come la maggior parte delle funzionalità vengano trasposte/convertite, credo serva comunque un disclaimer nel README tipo: 

"Alcune funzionalità presenti nei file Figma (.fig) potrebbero non essere presenti e/o non corrette nei file .sketch convertiti utilizzando la versione più recente di fig2sketch. È consigliato controllare sempre il risultato della conversione, e dichiarare lo stato delle risorse e questa eventualità agli utenti." 

Vedi quella che c'è nel README.md del kit UI. 

Immagino sarebbe utile anche nella GitHub Action. 

### Perché

Per trasparenza e dichiarazione responsabilità.

**Comment by astagi** [comment]
@Fupete aggiunto! per qualsiasi modifica vai pure libero.
